# Generated by Django 2.2.5 on 2019-09-06 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='url',
            new_name='track_url',
        ),
    ]
